### ISSUE TITLE
Error installing the package (and running it)

### ISSUE THREAD

**Issue by kuroi-hayabusa** [echamudi/cham-jp-deck#2]
Hi, I got errors when installing and running this application.
First I installed the latest nodejs package from https://nodejs.org/en/download/
Then I followed your instructions and I got the attached errors messages. I am also attaching the log file created after the installation command (npm install -g cham-jp-deck).

(soory I am not familiar with js)

[Installation Error Messages.txt](https://github.com/echamudi/cham-jp-deck/files/4870658/Installation.Error.Messages.txt)
[Execution Error Messages.txt](https://github.com/echamudi/cham-jp-deck/files/4870660/Execution.Error.Messages.txt)
[2020-07-03T16_01_33_559Z-debug.log](https://github.com/echamudi/cham-jp-deck/files/4870661/2020-07-03T16_01_33_559Z-debug.log)

**Comment by echamudi** [comment]
Hello,

Actually, you don't need to download the repository from github.

- Please delete the folder the following folder
    `C:\Users\USER\Downloads\GitHub\Echamudi\cham-jp-deck-master `

- Then create the following structure in desktop
    ```
    your_new_folder
    ├── JMdict_e
   └── kanjidic2.xml
    ```

- Open that `your_new_folder` in Windows cmd
    `c:\Users\(username)\Desktop\your_new_folder`

- Run the following commands
    ```
    npm uninstall -g cham-jp-deck
    npm install -g cham-jp-deck
    chamjpdeck-csv
    ```

**Comment by kuroi-hayabusa** [comment]
Hello, 
Obviously I am doing something wrong in my side. I followed your clear and simple instructions but I still got the same errors. 
Could it be that I did not setup my running environment properly? I am a complete novice to all this.
Thank you very much for your interest.

**Comment by echamudi** [comment]
Let's try installing the module locally instead of globally.

- Please try running `Install additional tools for node.js` from the start menu.

- Create the following structure in desktop
    ```
    your_new_folder
    ├── JMdict_e
   └── kanjidic2.xml
    ```

- Open that `your_new_folder` in Windows cmd
    `c:\Users\(your-user-name)\Desktop\your_new_folder`

- Run the following commands
    ```
    npm init -y
    npm install cham-jp-deck
    npx chamjpdeck-csv
    ```
- `cham_jp_deck.csv` file should appear.

**Comment by kuroi-hayabusa** [comment]
Hi Ezzat,
It worked. 
Thank you very much.
